In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode,iplot
import plotly.express as px
!pip install pandas_profiling
import pandas_profiling as pdp
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder

Requirement already satisfied: pandas_profiling in d:\anaconda\lib\site-packages (3.3.0)
Requirement already satisfied: requests<2.29,>=2.24.0 in d:\anaconda\lib\site-packages (from pandas_profiling) (2.27.1)
Requirement already satisfied: statsmodels<0.14,>=0.13.2 in d:\anaconda\lib\site-packages (from pandas_profiling) (0.13.2)
Requirement already satisfied: tangled-up-in-unicode==0.2.0 in d:\anaconda\lib\site-packages (from pandas_profiling) (0.2.0)
Requirement already satisfied: matplotlib<3.6,>=3.2 in d:\anaconda\lib\site-packages (from pandas_profiling) (3.5.1)
Requirement already satisfied: visions[type_image_path]==0.7.5 in d:\anaconda\lib\site-packages (from pandas_profiling) (0.7.5)
Requirement already satisfied: numpy<1.24,>=1.16.0 in d:\anaconda\lib\site-packages (from pandas_profiling) (1.21.5)
Requirement already satisfied: pydantic<1.10,>=1.8.1 in d:\anaconda\lib\site-packages (from pandas_profiling) (1.9.2)
Requirement already satisfied: tqdm<4.65,>=4.48.2 in d:\anaconda\lib\site-packages (from pandas_profiling) (4.64.0)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in d:\anaconda\lib\site-packages (from pandas_profiling) (2.11.3)
Requirement already satisfied: scipy<1.10,>=1.4.1 in d:\anaconda\lib\site-packages (from pandas_profiling) (1.7.3)
Requirement already satisfied: htmlmin==0.1.12 in d:\anaconda\lib\site-packages (from pandas_profiling) (0.1.12)
Requirement already satisfied: seaborn<0.12,>=0.10.1 in d:\anaconda\lib\site-packages (from pandas_profiling) (0.11.2)
Requirement already satisfied: pandas!=1.4.0,<1.5,>1.1 in d:\anaconda\lib\site-packages (from pandas_profiling) (1.4.2)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in d:\anaconda\lib\site-packages (from pandas_profiling) (6.0)
Requirement already satisfied: joblib~=1.1.0 in d:\anaconda\lib\site-packages (from pandas_profiling) (1.1.0)
Requirement already satisfied: multimethod<1.9,>=1.4 in d:\anaconda\lib\site-packages (from pandas_profiling) (1.8)
Requirement already satisfied: phik<0.13,>=0.11.1 in d:\anaconda\lib\site-packages (from pandas_profiling) (0.12.2)
Requirement already satisfied: missingno<0.6,>=0.4.2 in d:\anaconda\lib\site-packages (from pandas_profiling) (0.5.1)
Requirement already satisfied: networkx>=2.4 in d:\anaconda\lib\site-packages (from visions[type_image_path]==0.7.5->pandas_profiling) (2.7.1)
Requirement already satisfied: attrs>=19.3.0 in d:\anaconda\lib\site-packages (from visions[type_image_path]==0.7.5->pandas_profiling) (21.4.0)
Requirement already satisfied: imagehash in d:\anaconda\lib\site-packages (from visions[type_image_path]==0.7.5->pandas_profiling) (4.3.1)
Requirement already satisfied: Pillow in d:\anaconda\lib\site-packages (from visions[type_image_path]==0.7.5->pandas_profiling) (9.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in d:\anaconda\lib\site-packages (from jinja2<3.2,>=2.11.1->pandas_profiling) (2.0.1)
Requirement already satisfied: python-dateutil>=2.7 in d:\anaconda\lib\site-packages (from matplotlib<3.6,>=3.2->pandas_profiling) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\anaconda\lib\site-packages (from matplotlib<3.6,>=3.2->pandas_profiling) (1.3.2)
Requirement already satisfied: pyparsing>=2.2.1 in d:\anaconda\lib\site-packages (from matplotlib<3.6,>=3.2->pandas_profiling) (3.0.4)
Requirement already satisfied: packaging>=20.0 in d:\anaconda\lib\site-packages (from matplotlib<3.6,>=3.2->pandas_profiling) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in d:\anaconda\lib\site-packages (from matplotlib<3.6,>=3.2->pandas_profiling) (4.25.0)
Requirement already satisfied: cycler>=0.10 in d:\anaconda\lib\site-packages (from matplotlib<3.6,>=3.2->pandas_profiling) (0.11.0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas!=1.4.0,<1.5,>1.1->pandas_profiling) (2021.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\anaconda\lib\site-packages (from pydantic<1.10,>=1.8.1->pandas_profiling) (4.1.1)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.7->matplotlib<3.6,>=3.2->pandas_profiling) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\anaconda\lib\site-packages (from requests<2.29,>=2.24.0->pandas_profiling) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in d:\anaconda\lib\site-packages (from requests<2.29,>=2.24.0->pandas_profiling) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests<2.29,>=2.24.0->pandas_profiling) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests<2.29,>=2.24.0->pandas_profiling) (2021.10.8)
Requirement already satisfied: patsy>=0.5.2 in d:\anaconda\lib\site-packages (from statsmodels<0.14,>=0.13.2->pandas_profiling) (0.5.2)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from tqdm<4.65,>=4.48.2->pandas_profiling) (0.4.4)
Requirement already satisfied: PyWavelets in d:\anaconda\lib\site-packages (from imagehash->visions[type_image_path]==0.7.5->pandas_profiling) (1.3.0)

In [2]:
df = pd.read_csv("Order-2022-09-26.csv")

In [3]:
df

         user_id shipping_postal_code
0        90366.0               320119
1        90158.0               530451
2        90103.0               270043
3        90170.0               518153
4        90104.0               437603
...          ...                  ...
264336   98432.0               524167
264337  101498.0               650145
264338  101498.0               650145
264339   99431.0               437932
264340   98644.0               797394

[264341 rows x 2 columns]

In [7]:
df["user_id"].value_counts()

91552.0     610
101818.0    428
103594.0    349
91485.0     349
103566.0    348
           ...
100048.0      1
123418.0      1
123417.0      1
121557.0      1
96395.0       1
Name: user_id, Length: 32094, dtype: int64

In [5]:
df1 = df.drop_duplicates(subset=['user_id'],keep='first',inplace=False)

In [6]:
df1

         user_id shipping_postal_code
0        90366.0               320119
1        90158.0               530451
2        90103.0               270043
3        90170.0               518153
4        90104.0               437603
...          ...                  ...
264312  133809.0               600331
264315  133834.0               310201
264316  133836.0               416883
264324  133837.0               530465
264332  133838.0               329853

[32095 rows x 2 columns]

In [8]:
df1.to_csv("postal_code.csv")