In [1]:
import pandas as pd
import numpy as np

In [3]:
f = pd.read_csv('C:/Users/chenyuzhou/Desktop/final.csv')

In [4]:
f.columns

Index(['user_id', 'order_times', 'order_spend', 'total_comment', 'sub_times',
       'voucher_times', 'cancelled', 'login', 'view_product',
       'add_item_to_cart', 'points_added', 'view_per_login', 'item_per_view',
       'points_per_add', 'spend_per_order', 'cluster'],
      dtype='object')

In [5]:
f['cluster'].value_counts()

4    15306
5    10977
1     7522
6     5117
3     1959
7     1540
2     1286
9      285
8       55
0       41
Name: cluster, dtype: int64

In [6]:
rest=['user_id','order_times', 'order_spend', 'total_comment', 'sub_times',
       'voucher_times', 'cancelled', 'login', 'view_product',
       'add_item_to_cart', 'points_added', 'view_per_login', 'item_per_view',
       'points_per_add', 'spend_per_order', 'cluster']

In [7]:
df = pd.DataFrame(columns=rest)

In [8]:
df

Empty DataFrame
Columns: [user_id, order_times, order_spend, total_comment, sub_times, voucher_times, cancelled, login, view_product, add_item_to_cart, points_added, view_per_login, item_per_view, points_per_add, spend_per_order, cluster]
Index: []

In [9]:
for i in range(10):
    r= f[f['cluster']==i].mean().values
    df.loc[len(df)] = r

In [10]:
df

,user_id,order_times,order_spend,total_comment,sub_times,voucher_times,cancelled,login,view_product,add_item_to_cart,points_added,view_per_login,item_per_view,points_per_add,spend_per_order,cluster
0,121389.585366,1.097561,1817.253415,0.000000,0.000000,0.439024,0.000000,1.902439,9.463415,2.951220,0.878049,4.619977,0.310262,0.447084,1718.488049,0.0
1,118410.300984,1.225605,50.469633,0.086812,0.101037,0.047062,0.082292,1.628157,14.062483,4.833289,0.810556,8.948512,0.359317,0.204460,29.215364,1.0
2,118499.741835,1.715397,61.181913,0.461897,0.479782,0.247278,0.452566,1.310264,33.929238,9.905910,1.055988,25.940046,0.325468,0.121347,32.356744,2.0
3,115844.616641,2.124553,32.175258,0.274119,0.312404,0.088310,0.270036,1.710056,1.140378,2.713119,1.295559,0.976087,2.416357,0.443900,5.217035,3.0
4,98585.271789,3.519992,50.333551,0.048151,0.087025,0.000000,0.021560,0.486999,0.874494,0.160983,0.069385,0.433276,0.026270,0.033445,14.135517,4.0
5,115297.200055,4.325043,75.139841,0.349549,0.413501,0.000091,0.330874,3.503507,5.885579,2.786189,2.526829,2.148056,0.670098,0.990940,15.302308,5.0
6,114906.989838,6.657221,128.975695,1.320109,1.422122,1.129764,1.290014,6.780926,20.654094,7.488372,4.450068,4.144144,0.468622,0.933949,22.329740,6.0
7,106895.888312,46.003247,791.836130,5.020779,5.270779,1.012987,4.710390,24.059740,51.105844,18.081169,29.026623,3.070485,0.416093,2.892189,23.005461,7.0
8,111301.345455,65.800000,1241.810545,34.345455,35.072727,7.418182,33.745455,46.290909,172.127273,60.872727,26.109091,4.304871,0.407091,0.438751,18.449425,8.0
9,98521.505263,136.189474,2003.761474,1.642105,2.340351,0.270175,1.371930,23.084211,17.143860,9.371930,90.564912,0.852818,0.782349,34.093958,16.337534,9.0

In [11]:
df = df.drop(columns=['user_id'])

In [12]:
df

,order_times,order_spend,total_comment,sub_times,voucher_times,cancelled,login,view_product,add_item_to_cart,points_added,view_per_login,item_per_view,points_per_add,spend_per_order,cluster
0,1.097561,1817.253415,0.000000,0.000000,0.439024,0.000000,1.902439,9.463415,2.951220,0.878049,4.619977,0.310262,0.447084,1718.488049,0.0
1,1.225605,50.469633,0.086812,0.101037,0.047062,0.082292,1.628157,14.062483,4.833289,0.810556,8.948512,0.359317,0.204460,29.215364,1.0
2,1.715397,61.181913,0.461897,0.479782,0.247278,0.452566,1.310264,33.929238,9.905910,1.055988,25.940046,0.325468,0.121347,32.356744,2.0
3,2.124553,32.175258,0.274119,0.312404,0.088310,0.270036,1.710056,1.140378,2.713119,1.295559,0.976087,2.416357,0.443900,5.217035,3.0
4,3.519992,50.333551,0.048151,0.087025,0.000000,0.021560,0.486999,0.874494,0.160983,0.069385,0.433276,0.026270,0.033445,14.135517,4.0
5,4.325043,75.139841,0.349549,0.413501,0.000091,0.330874,3.503507,5.885579,2.786189,2.526829,2.148056,0.670098,0.990940,15.302308,5.0
6,6.657221,128.975695,1.320109,1.422122,1.129764,1.290014,6.780926,20.654094,7.488372,4.450068,4.144144,0.468622,0.933949,22.329740,6.0
7,46.003247,791.836130,5.020779,5.270779,1.012987,4.710390,24.059740,51.105844,18.081169,29.026623,3.070485,0.416093,2.892189,23.005461,7.0
8,65.800000,1241.810545,34.345455,35.072727,7.418182,33.745455,46.290909,172.127273,60.872727,26.109091,4.304871,0.407091,0.438751,18.449425,8.0
9,136.189474,2003.761474,1.642105,2.340351,0.270175,1.371930,23.084211,17.143860,9.371930,90.564912,0.852818,0.782349,34.093958,16.337534,9.0

In [13]:
df['population']=[41, 7522, 1286, 1959, 15306, 10977, 5117, 1540,55,285]

In [14]:
df

,order_times,order_spend,total_comment,sub_times,voucher_times,cancelled,login,view_product,add_item_to_cart,points_added,view_per_login,item_per_view,points_per_add,spend_per_order,cluster,population
0,1.097561,1817.253415,0.000000,0.000000,0.439024,0.000000,1.902439,9.463415,2.951220,0.878049,4.619977,0.310262,0.447084,1718.488049,0.0,41
1,1.225605,50.469633,0.086812,0.101037,0.047062,0.082292,1.628157,14.062483,4.833289,0.810556,8.948512,0.359317,0.204460,29.215364,1.0,7522
2,1.715397,61.181913,0.461897,0.479782,0.247278,0.452566,1.310264,33.929238,9.905910,1.055988,25.940046,0.325468,0.121347,32.356744,2.0,1286
3,2.124553,32.175258,0.274119,0.312404,0.088310,0.270036,1.710056,1.140378,2.713119,1.295559,0.976087,2.416357,0.443900,5.217035,3.0,1959
4,3.519992,50.333551,0.048151,0.087025,0.000000,0.021560,0.486999,0.874494,0.160983,0.069385,0.433276,0.026270,0.033445,14.135517,4.0,15306
5,4.325043,75.139841,0.349549,0.413501,0.000091,0.330874,3.503507,5.885579,2.786189,2.526829,2.148056,0.670098,0.990940,15.302308,5.0,10977
6,6.657221,128.975695,1.320109,1.422122,1.129764,1.290014,6.780926,20.654094,7.488372,4.450068,4.144144,0.468622,0.933949,22.329740,6.0,5117
7,46.003247,791.836130,5.020779,5.270779,1.012987,4.710390,24.059740,51.105844,18.081169,29.026623,3.070485,0.416093,2.892189,23.005461,7.0,1540
8,65.800000,1241.810545,34.345455,35.072727,7.418182,33.745455,46.290909,172.127273,60.872727,26.109091,4.304871,0.407091,0.438751,18.449425,8.0,55
9,136.189474,2003.761474,1.642105,2.340351,0.270175,1.371930,23.084211,17.143860,9.371930,90.564912,0.852818,0.782349,34.093958,16.337534,9.0,285

In [67]:
df.columns

Index(['order_times', 'order_spend', 'total_comment', 'sub_times',
       'voucher_times', 'cancelled', 'login', 'view_product',
       'add_item_to_cart', 'points_added', 'view_per_login', 'item_per_view',
       'points_per_add', 'spend_per_order', 'cluster', 'population'],
      dtype='object')

In [68]:
ranks=['order_times', 'order_spend', 'total_comment', 'sub_times',
       'voucher_times', 'cancelled', 'login', 'view_product',
       'add_item_to_cart', 'points_added', 'view_per_login', 'item_per_view',
       'points_per_add', 'spend_per_order']

In [77]:
r = df

In [76]:
for i in ranks:
    print('rank_',i)

rank_ order_times
rank_ order_spend
rank_ total_comment
rank_ sub_times
rank_ voucher_times
rank_ cancelled
rank_ login
rank_ view_product
rank_ add_item_to_cart
rank_ points_added
rank_ view_per_login
rank_ item_per_view
rank_ points_per_add
rank_ spend_per_order

In [80]:
for i in ranks:    
    r['rank_',i] = r[i].rank(method="first")

In [81]:
r

,order_times,order_spend,total_comment,sub_times,voucher_times,cancelled,login,view_product,add_item_to_cart,points_added,...,"(rank_, voucher_times)","(rank_, cancelled)","(rank_, login)","(rank_, view_product)","(rank_, add_item_to_cart)","(rank_, points_added)","(rank_, view_per_login)","(rank_, item_per_view)","(rank_, points_per_add)","(rank_, spend_per_order)"
0,1.097561,1817.253415,0.000000,0.000000,0.439024,0.000000,1.902439,9.463415,2.951220,0.878049,...,7.0,1.0,5.0,4.0,4.0,3.0,8.0,2.0,6.0,10.0
1,1.225605,50.469633,0.086812,0.101037,0.047062,0.082292,1.628157,14.062483,4.833289,0.810556,...,3.0,3.0,3.0,5.0,5.0,2.0,9.0,4.0,3.0,8.0
2,1.715397,61.181913,0.461897,0.479782,0.247278,0.452566,1.310264,33.929238,9.905910,1.055988,...,5.0,6.0,2.0,8.0,8.0,4.0,10.0,3.0,2.0,9.0
3,2.124553,32.175258,0.274119,0.312404,0.088310,0.270036,1.710056,1.140378,2.713119,1.295559,...,4.0,4.0,4.0,2.0,2.0,5.0,3.0,10.0,5.0,1.0
4,3.519992,50.333551,0.048151,0.087025,0.000000,0.021560,0.486999,0.874494,0.160983,0.069385,...,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0
5,4.325043,75.139841,0.349549,0.413501,0.000091,0.330874,3.503507,5.885579,2.786189,2.526829,...,2.0,5.0,6.0,3.0,3.0,6.0,4.0,8.0,8.0,3.0
6,6.657221,128.975695,1.320109,1.422122,1.129764,1.290014,6.780926,20.654094,7.488372,4.450068,...,9.0,7.0,7.0,7.0,6.0,7.0,6.0,7.0,7.0,6.0
7,46.003247,791.836130,5.020779,5.270779,1.012987,4.710390,24.059740,51.105844,18.081169,29.026623,...,8.0,9.0,9.0,9.0,9.0,9.0,5.0,6.0,9.0,7.0
8,65.800000,1241.810545,34.345455,35.072727,7.418182,33.745455,46.290909,172.127273,60.872727,26.109091,...,10.0,10.0,10.0,10.0,10.0,8.0,7.0,5.0,4.0,5.0
9,136.189474,2003.761474,1.642105,2.340351,0.270175,1.371930,23.084211,17.143860,9.371930,90.564912,...,6.0,8.0,8.0,6.0,7.0,10.0,2.0,9.0,10.0,4.0

In [82]:
outputpath='C:/Users/chenyuzhou/Desktop/analysis.csv'
r.to_csv(outputpath,sep=',',index=False,header=True)